[package]
name = "zero-template"
version = "3.0.0"
description = "A fresh FRAME-based Substrate node, ready for hacking."
authors = ["ZERO <https://github.com/playzero>"]
homepage = "https://zero.io/"
edition = "2021"
license = "Unlicense"
publish = false
repository = "https://github.com/playzero/zero-node-template/"
build = "build.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "zero-template"

[dependencies]
structopt = "0.3.25"

sc-cli = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01", features = ["wasmtime"] }
sp-core = { version = "4.1.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-executor = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01", features = ["wasmtime"] }
sc-service = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01", features = ["wasmtime"] }
sc-telemetry = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-keystore = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-transaction-pool = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-transaction-pool-api = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-consensus-aura = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-consensus-aura = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-consensus = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-consensus = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-finality-grandpa = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-finality-grandpa = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-client-api = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-runtime = { version = "4.0.0", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-timestamp = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }

# These dependencies are used for the node template's RPCs
jsonrpc-core = "18.0.0"
sc-rpc = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-api = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-rpc-api = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-blockchain = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-block-builder = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-basic-authorship = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
substrate-frame-rpc-system = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
pallet-transaction-payment-rpc = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }

# These dependencies are used for runtime benchmarking
frame-benchmarking = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
frame-benchmarking-cli = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }

zero-template-runtime = { path = "../runtime" }

[build-dependencies]
substrate-build-script-utils = { version = "3.0.0", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }

[features]
default = []
runtime-benchmarks = [
	"zero-template-runtime/runtime-benchmarks",
]
