[package]
name = "node-testing"
version = "3.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Test utilities for Substrate node."
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
publish = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0" }

node-executor = { version = "3.0.0-dev", path = "../executor" }
node-primitives = { version = "2.0.0", path = "../primitives" }
node-runtime = { version = "3.0.0-dev", path = "../runtime" }

sc-service = { version = "0.10.0-dev", features = ["test-helpers", "db", ], git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-client-db = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01", features = ["kvdb-rocksdb", "parity-db" ] }
sc-client-api = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-consensus = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-keyring = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-core = { version = "4.1.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-io = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-runtime = { version = "4.0.0", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-executor = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01", features = ["wasmtime"] }
sp-consensus = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
frame-system = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
substrate-test-client = { version = "2.0.0", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
pallet-transaction-payment = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
pallet-asset-tx-payment = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-api = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-timestamp = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-block-builder = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-block-builder = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-inherents = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-blockchain = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
log = "0.4.8"
tempfile = "3.1.0"
fs_extra = "1"
futures = "0.3.1"
