[package]
name = "node-primitives"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }

frame-system = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-application-crypto = { version = "4.0.0", default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-core = { version = "4.1.0-dev", default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-runtime = { version = "4.0.0", default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }

[features]
default = ["std"]
std = [
	"codec/std",
	"scale-info/std",
	"frame-system/std",
	"sp-application-crypto/std",
	"sp-core/std",
	"sp-runtime/std",
]
