[package]
name = "zero-template-runtime"
version = "3.0.0"
description = "A fresh FRAME-based Substrate runtime, ready for hacking."
authors = ["Substrate DevHub <https://github.com/substrate-developer-hub>"]
homepage = "https://substrate.io/"
edition = "2021"
license = "Unlicense"
publish = false
repository = "https://github.com/substrate-developer-hub/substrate-node-template/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", default-features = false, features = ["derive"] }
scale-info = { default-features = false, features = ["derive"] }

pallet-aura = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
pallet-balances = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
pallet-grandpa = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
pallet-randomness-collective-flip = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
pallet-sudo = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
pallet-timestamp = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
pallet-transaction-payment = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
frame-executive = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-api = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01", default-features = false }
sp-consensus-aura = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-inherents = { git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01", default-features = false }
sp-offchain = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-session = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-transaction-pool = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-version = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }

# Used for the node template's RPCs
frame-system-rpc-runtime-api = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
pallet-transaction-payment-rpc-runtime-api = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }

# Used for runtime benchmarking
frame-benchmarking = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01", optional = true }
frame-system-benchmarking = { default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01", optional = true }
hex-literal = { version = "0.3.4", optional = true }

pallet-template = { default-features = false, path =  "../pallets/template" }

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01", version = "5.0.0-dev" }
# substrate-wasm-builder = { version = "5.0.0-dev", path = "../../../utils/wasm-builder" }

[features]
default = ["std"]
std = [
	"codec/std",
	"scale-info/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"pallet-aura/std",
	"pallet-balances/std",
	"pallet-grandpa/std",
	"pallet-randomness-collective-flip/std",
	"pallet-sudo/std",
	"pallet-template/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-transaction-payment/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system-benchmarking",
	"frame-system/runtime-benchmarks",
	"hex-literal",
	"pallet-balances/runtime-benchmarks",
	"pallet-template/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
